repos:
  # Format C++ code with Clang-Format - automatically applying the changes
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.8
    hooks:
      - id: clang-format
        args:
        - --style=Mozilla
        exclude: ^ext/

  # Add some general purpose useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Unify file endings
      - id: end-of-file-fixer
      # Make sure that contained YAML files are well-formed
      - id: check-yaml
      # Trim trailing whitespace of all sorts
      - id: trailing-whitespace

  # GitHub Actions Workflow linter
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
