version: 2

sphinx:
  configuration: doc/conf.py

formats: all

submodules:
  include: all
  recursive: true

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: doc/requirements-rtd.txt
