name: CI

on:
  # We run CI on pushes to the main branch
  push:
    branches:
      - main
  # and on all pull requests to the main branch
  pull_request:
    branches:
      - main
  # as well as upon manual triggers through the 'Actions' tab of the Github UI
  workflow_dispatch:

jobs:
  build-and-test:
    name: Testing on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v7

    - name: Install Doxygen
      uses: ssciwr/doxygen-install@v2

    - name: Configure cmake
      shell: bash
      run: cmake --preset test

    - name: Build
      shell: bash
      run: cmake --build --preset test

    - name: Run tests
      shell: bash
      run: ctest --preset test

  coverage-test:
    name: Coverage Testing
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Install LCov
      run: |
        sudo apt-get install -y lcov

    - name: Install Doxygen
      uses: ssciwr/doxygen-install@v2

    - name: Configure cmake
      shell: bash
      run: |
        cmake --preset test \
          -DCMAKE_CXX_FLAGS="--coverage -fprofile-update=atomic -O0 -g" \
          -DCMAKE_EXE_LINKER_FLAGS="--coverage"

    - name: Build
      shell: bash
      run: cmake --build --preset test

    - name: Run tests
      shell: bash
      run: ctest --preset test

    - name: Collect coverage report
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        lcov --directory ./build/src --capture --output-file coverage.info --ignore-errors mismatch,unused --exclude '*/catch2/*'

    - name: Upload C++ coverage to Codecov
      uses: codecov/codecov-action@v7
      with:
        fail_ci_if_error: true
        files: ${{github.workspace}}/coverage.info
